const settingsScreenStyles = {
  root: "mx-auto max-w-4xl",
  element1: "space-y-6",
  element2: "overflow-hidden",
  element3: "border-b border-[var(--line)] px-5 py-4",
  element4: "font-semibold text-[var(--ink)]",
  element5: "mt-1 text-sm text-[var(--muted)]",
  element6: "grid gap-5 p-5 sm:grid-cols-2 sm:p-7",
  element7: "sm:col-span-2",
  element8: "mb-3 text-sm font-medium text-[var(--ink)]",
  element9: "grid gap-2 sm:grid-cols-3",
  element10: "size-4",
  element11: "p-5 sm:p-7",
  element12: "flex items-start gap-3",
  element13: "mt-0.5 size-5 text-[var(--accent)]",
  element14: "font-semibold text-[var(--ink)]",
  element15: "mt-1 text-sm text-[var(--muted)]",
  element16: "mt-5 divide-y divide-[var(--line)]",
  element17: "p-5 sm:p-7",
  element18: "flex items-start gap-3",
  element19: "mt-0.5 size-5 text-[var(--accent)]",
  element20: "font-semibold text-[var(--ink)]",
  element21: "mt-1 text-sm text-[var(--muted)]",
  element22: "mt-5 space-y-4",
  element23: "size-4",
  element24: "border-t border-[var(--line)] pt-4",
  themeButtonActive: "border-[var(--accent)] bg-[var(--accent-soft)] text-[var(--accent-dark)]",
  themeButtonInactive: "border-[var(--line)] text-[var(--muted)]",
  themeButtonBase: "flex items-center gap-3 rounded-lg border p-3 text-left text-sm",
};

export { settingsScreenStyles };
