const dashboardScreenStyles = {
  root: "space-y-6",
  headerIcon: "size-4",
  statsGrid: "grid gap-4 sm:grid-cols-2 xl:grid-cols-4",
  mainGrid: "mt-8 grid gap-6 xl:grid-cols-[1.35fr_0.65fr]",
  queuesCard: "overflow-hidden",
  cardHeader: "flex items-center justify-between border-b border-[var(--line)] px-5 py-4",
  cardTitle: "font-semibold text-[var(--ink)]",
  cardSubtitle: "mt-1 text-xs text-[var(--muted)]",
  viewAllLink: "text-sm font-semibold text-[var(--accent-dark)]",
  queuesList: "divide-y divide-[var(--line)]",
  queueItem: "flex flex-col gap-4 px-5 py-5 sm:flex-row sm:items-center sm:justify-between",
  queueMain: "flex items-center gap-3",
  queueBadge: "flex size-10 items-center justify-center rounded-lg bg-[var(--accent-soft)] text-xs font-semibold text-[var(--accent-dark)]",
  queueLink: "font-medium text-[var(--ink)] hover:text-[var(--accent-dark)]",
  queueMeta: "mt-1 text-xs text-[var(--muted)]",
  queueStats: "flex items-center gap-6",
  queueStatLabel: "text-xs text-[var(--muted)]",
  queueStatValue: "mt-1 font-semibold text-[var(--ink)]",
  queueAvgWaitWrapper: "hidden sm:block",
  quickActionsCard: "p-5",
  quickActionsHeader: "flex items-center justify-between",
  quickActionsTitle: "font-semibold text-[var(--ink)]",
  quickActionsSubtitle: "mt-1 text-xs text-[var(--muted)]",
  quickActionsList: "mt-5 space-y-2",
  actionBtn: "w-full justify-between",
  actionBtnContent: "flex items-center gap-2",
  actionBtnIcon: "size-4 text-[var(--accent)]",
  actionArrowIcon: "size-4",
  completionSection: "mt-7 border-t border-[var(--line)] pt-5",
  completionHeader: "flex items-center justify-between text-sm",
  completionLabel: "text-[var(--muted)]",
  completionValue: "font-semibold text-[var(--ink)]",
  completionProgress: "mt-3",
  bottomGrid: "mt-8 grid gap-6 lg:grid-cols-2",
  activityHeader: "flex items-center justify-between border-b border-[var(--line)] px-5 py-4",
  activityTitle: "font-semibold text-[var(--ink)]",
  activityHeaderIcon: "size-4 text-[var(--muted)]",
  activityList: "divide-y divide-[var(--line)]",
  activityItem: "flex items-center gap-3 px-5 py-4",
  activityDot: "size-2 rounded-full bg-[var(--accent)]",
  activityContent: "flex-1",
  activityText: "text-sm text-[var(--ink)]",
  activityTime: "mt-1 text-xs text-[var(--muted)]",
  perfCard: "p-5",
  perfHeader: "flex items-center justify-between",
  perfTitle: "font-semibold text-[var(--ink)]",
  perfSubtitle: "mt-1 text-xs text-[var(--muted)]",
  perfDetailsLink: "text-sm font-semibold text-[var(--accent-dark)]",
  perfChart: "mt-8 flex h-32 items-end gap-3",
  perfColumn: "flex flex-1 flex-col items-center gap-2",
  perfBar: "w-full rounded-t-md bg-[var(--accent-soft)]",
  perfLabel: "text-[10px] text-[var(--muted)]",
};

export { dashboardScreenStyles };
