const queuesScreenStyles = {
  root: "space-y-6",
  headerIcon: "size-4",
  filterRow: "mb-5 flex flex-col gap-3 lg:flex-row",
  searchWrapper: "w-full lg:max-w-sm",
  filterGroup: "grid grid-cols-2 gap-3 sm:flex",
  card: "overflow-hidden",
  tableWrapper: "hidden overflow-x-auto md:block",
  table: "w-full text-left",
  tableHeader: "border-b border-[var(--line)] bg-[var(--surface-muted)]",
  th: "px-5 py-3 text-xs font-semibold uppercase tracking-wide text-[var(--muted)]",
  tbody: "divide-y divide-[var(--line)]",
  tr: "transition hover:bg-[var(--surface-muted)]",
  tdMain: "px-5 py-4",
  queueLink: "font-medium text-[var(--ink)] hover:text-[var(--accent-dark)]",
  queueMeta: "mt-1 text-xs text-[var(--muted)]",
  tdBadge: "px-5 py-4",
  tdText: "px-5 py-4 text-sm text-[var(--ink)]",
  tdMuted: "px-5 py-4 text-sm text-[var(--muted)]",
  tdActions: "px-5 py-4 text-right",
  mobileList: "divide-y divide-[var(--line)] md:hidden",
  mobileCard: "space-y-4 p-5",
  mobileHeader: "flex items-start justify-between gap-3",
  mobileTitle: "font-medium text-[var(--ink)]",
  mobileSub: "mt-1 text-xs text-[var(--muted)]",
  mobileGrid: "grid grid-cols-2 gap-3 rounded-lg bg-[var(--surface-muted)] p-3 text-sm",
  mobileLabel: "text-xs text-[var(--muted)]",
  mobileVal: "mt-1 font-semibold",
  mobileActions: "flex gap-2",
  mobileBtn: "flex-1",
};

export { queuesScreenStyles };
