const createQueueScreenStyles = {
  root: "mx-auto max-w-4xl",
  backLink: "mb-6 inline-flex items-center gap-2 text-sm font-medium text-[var(--muted)] hover:text-[var(--ink)]",
  backIcon: "size-4",
  header: "mb-8",
  eyebrow: "mb-2 text-xs font-semibold uppercase tracking-[0.14em] text-[var(--accent)]",
  title: "text-3xl font-semibold tracking-[-0.04em] text-[var(--ink)]",
  description: "mt-2 text-sm leading-6 text-[var(--muted)]",
  stepper: "mb-8 flex items-center gap-2 overflow-x-auto pb-1",
  activeStep: "flex items-center gap-2 whitespace-nowrap text-sm font-semibold text-[var(--accent-dark)]",
  activeStepNumber: "flex size-7 items-center justify-center rounded-full bg-[var(--primary)] text-xs text-[var(--primary-foreground)]",
  divider: "h-px w-10 bg-[var(--line-strong)]",
  stepItem: "flex items-center gap-2 whitespace-nowrap text-sm text-[var(--muted)]",
  stepNumber: "flex size-7 items-center justify-center rounded-full bg-[var(--surface-muted)] text-xs",
  form: "space-y-6",
  card: "p-5 sm:p-7",
  cardTitle: "text-lg font-semibold text-[var(--ink)]",
  cardSubtitle: "mt-1 text-sm text-[var(--muted)]",
  grid2: "mt-6 grid gap-5 sm:grid-cols-2",
  fullCol: "sm:col-span-2",
  inputLabel: "block",
  labelRow: "mb-2 flex items-center gap-2 text-sm font-medium text-[var(--ink)]",
  labelIcon: "size-3.5 text-[var(--muted)]",
  inputField: "h-10 w-full rounded-lg border border-[var(--line)] px-3 text-sm",
  optionsList: "mt-4 divide-y divide-[var(--line)]",
  infoBox: "mt-4 flex gap-2 rounded-lg bg-[var(--accent-soft)] p-3 text-xs leading-5 text-[var(--accent-dark)]",
  infoIcon: "mt-0.5 size-4 shrink-0",
  actions: "mt-6 flex flex-col-reverse justify-end gap-3 sm:flex-row",
  submitIcon: "size-4",
};

export { createQueueScreenStyles };
