const analyticsScreenStyles = {
  root: "space-y-6",
  selectWrapper: "w-40",
  statsGrid: "grid gap-4 sm:grid-cols-2 xl:grid-cols-4",
  chartSectionGrid: "mt-8 grid gap-6 xl:grid-cols-[1.3fr_0.7fr]",
  chartCard: "p-5 sm:p-6",
  cardTitle: "font-semibold text-[var(--ink)]",
  cardSubtitle: "mt-1 text-xs text-[var(--muted)]",
  barChartContainer: "mt-8 flex h-56 items-end gap-2 sm:gap-4",
  barColumn: "flex h-full flex-1 flex-col items-center justify-end gap-2",
  barFill: "w-full rounded-t-md bg-[var(--accent)]/80 transition hover:bg-[var(--accent)]",
  barLabel: "text-[10px] text-[var(--muted)]",
  progressCard: "p-5 sm:p-6",
  progressCardTitle: "font-semibold text-[var(--ink)]",
  progressCardSubtitle: "mt-1 text-xs text-[var(--muted)]",
  progressList: "mt-7 space-y-6",
  bottomGrid: "mt-6 grid gap-6 lg:grid-cols-2",
  peakHoursCard: "p-5",
  peakHoursTitle: "font-semibold text-[var(--ink)]",
  peakHoursSubtitle: "mt-1 text-xs text-[var(--muted)]",
  peakHoursList: "mt-6 space-y-4",
  peakHourRow: "flex items-center gap-3 text-sm",
  peakHourLabel: "w-12 text-[var(--muted)]",
  peakHourTrack: "h-2 flex-1 rounded-full bg-[var(--surface-muted)]",
  peakHourBar: "h-full rounded-full bg-[var(--accent-light)]",
  peakHourValue: "w-8 text-right text-xs text-[var(--muted)]",
  avgWaitCard: "p-5",
  avgWaitTitle: "font-semibold text-[var(--ink)]",
  avgWaitSubtitle: "mt-1 text-xs text-[var(--muted)]",
  avgWaitValue: "mt-8 text-4xl font-semibold tracking-[-0.05em] text-[var(--ink)]",
  avgWaitChange: "mt-2 text-sm text-[var(--success)]",
};

export { analyticsScreenStyles };
