const joinQueueScreenStyles = {
  root: "min-h-screen bg-[var(--background)] px-[var(--page-padding)] py-[var(--page-section-gap)] sm:px-[var(--page-padding-tablet)]",
  container: "mx-auto max-w-2xl",
  backLink: "inline-flex items-center gap-2 text-sm font-medium text-[var(--muted)] hover:text-[var(--ink)]",
  backIcon: "size-4",
  header: "mt-12 text-center",
  iconWrapper: "mx-auto flex size-14 items-center justify-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]",
  queueIcon: "size-7",
  title: "mt-6 text-3xl font-semibold tracking-[-0.04em] text-[var(--ink)]",
  subtitle: "mt-3 text-sm text-[var(--muted)]",
  content: "mt-10 space-y-5",
  card: "p-5 sm:p-7",
  stepHeader: "mb-6 flex items-center gap-3",
  stepNumber: "flex size-8 items-center justify-center rounded-full bg-[var(--primary)] text-sm font-semibold text-[var(--primary-foreground)]",
  stepTitle: "font-semibold text-[var(--ink)]",
  stepSubtitle: "text-xs text-[var(--muted)]",
  form: "space-y-5",
  submitBtn: "mt-6 w-full",
  submitIcon: "size-4",
  infoCard: "p-5",
  infoRow: "flex items-start gap-3",
  infoIcon: "mt-0.5 size-5 text-[var(--accent)]",
  infoTitle: "text-sm font-medium text-[var(--ink)]",
  infoText: "mt-1 text-sm text-[var(--muted)]",
  successCard: "p-8 text-center",
  checkIcon: "mx-auto size-10 text-[var(--success)]",
  successTitle: "mt-4 text-2xl font-semibold text-[var(--ink)]",
  successSubtitle: "mt-2 text-sm text-[var(--muted)]",
  ticketNumber: "mt-8 text-6xl font-semibold tracking-[-0.06em] text-[var(--accent)]",
  grid2: "mt-8 grid grid-cols-2 gap-3 text-left",
  statBox: "rounded-xl bg-[var(--surface-muted)] p-4",
  statLabel: "text-xs text-[var(--muted)]",
  statValue: "mt-1 text-xl font-semibold",
};

export { joinQueueScreenStyles };
