const dashboardShellStyles = {
  root: "min-h-screen bg-[var(--paper)] text-[var(--ink)]",
  backdrop: "fixed inset-0 z-30 bg-[var(--overlay)] lg:hidden",
  sidebar: "fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r border-[var(--border)] bg-[var(--surface)] transition-transform lg:translate-x-0",
  sidebarOpen: "translate-x-0",
  sidebarClosed: "-translate-x-full",
  sidebarHeader: "flex h-20 items-center justify-between border-b border-[var(--line)] px-6",
  logoLink: "flex items-center gap-2.5 text-sm font-semibold tracking-tight",
  logoBadge: "flex size-8 items-center justify-center rounded-lg bg-[var(--primary)] text-[var(--primary-foreground)]",
  logoDot: "size-2 rounded-full bg-[var(--primary-foreground)]",
  closeButton: "rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--surface-muted)] lg:hidden",
  closeIcon: "size-5",
  nav: "flex-1 space-y-7 overflow-y-auto px-3 py-6",
  groupLabel: "mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.14em] text-[var(--muted)]",
  groupItems: "space-y-1",
  navItem: "flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition",
  navItemActive: "bg-[var(--accent-soft)] text-[var(--accent-dark)]",
  navItemInactive: "text-[var(--muted)] hover:bg-[var(--surface-muted)] hover:text-[var(--ink)]",
  navIcon: "size-[18px]",
  sidebarFooter: "border-t border-[var(--line)] p-4",
  accountWrapper: "relative",
  accountButton: "flex w-full items-center gap-3 rounded-lg p-2 text-left hover:bg-[var(--surface-muted)]",
  avatar: "flex size-9 items-center justify-center rounded-full bg-[var(--accent-soft)] text-xs font-semibold text-[var(--accent-dark)]",
  accountInfo: "min-w-0 flex-1",
  accountName: "truncate text-sm font-semibold text-[var(--ink)]",
  accountEmail: "truncate text-xs text-[var(--muted)]",
  chevronIcon: "size-4 text-[var(--muted)] transition-transform",
  chevronOpen: "rotate-180",
  dropdownMenu: "absolute bottom-14 left-0 right-0 rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface-elevated)] p-1 shadow-[var(--shadow-lg)]",
  dropdownItem: "block rounded-md px-3 py-2 text-sm text-[var(--muted)] hover:bg-[var(--surface-muted)]",
  logoutButton: "flex w-full items-center gap-2 rounded-md px-3 py-2 text-sm text-[var(--muted)] hover:bg-[var(--surface-muted)]",
  logoutIcon: "size-4",
  mainWrapper: "lg:pl-64",
  header: "sticky top-0 z-20 flex h-20 items-center justify-between border-b border-[var(--line)] bg-[var(--paper)]/90 px-5 backdrop-blur-md sm:px-8",
  headerLeft: "flex items-center gap-3",
  openSidebarBtn: "rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--surface-muted)] lg:hidden",
  menuIcon: "size-5",
  searchWrapper: "hidden w-64 sm:block",
  headerRight: "flex items-center gap-2",
  headerIconButton: "rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--surface-muted)]",
  headerIcon: "size-5",
  notificationsButton: "relative rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--surface-muted)]",
  unreadDot: "absolute right-1.5 top-1.5 size-1.5 rounded-full bg-[var(--accent)]",
  headerAvatar: "ml-2 flex size-9 items-center justify-center rounded-full bg-[var(--accent-soft)] text-xs font-semibold text-[var(--accent-dark)]",
  mainContent: "mx-auto max-w-7xl px-[var(--page-padding)] py-[var(--page-section-gap)] sm:px-[var(--page-padding-tablet)] lg:px-[var(--page-padding-desktop)]",
};

export { dashboardShellStyles };
