const queueManagementScreenStyles = {
  root: "space-y-6",
  backLink: "mb-6 inline-flex items-center gap-2 text-sm font-medium text-[var(--muted)] hover:text-[var(--ink)]",
  backIcon: "size-4",
  actionsGroup: "flex flex-wrap gap-2",
  actionIcon: "size-4",
  metaBar: "mb-6 flex flex-wrap items-center gap-3",
  badgeDot: "size-1.5 rounded-full bg-current",
  metaText: "text-sm text-[var(--muted)]",
  metaStrong: "text-[var(--ink)]",
  statsGrid: "grid gap-4 sm:grid-cols-3",
  mainGrid: "mt-8 grid gap-6 xl:grid-cols-[1fr_340px]",
  leftCol: "space-y-6",
  card: "overflow-hidden",
  nowServingHeader: "flex flex-col gap-4 border-b border-[var(--line)] px-5 py-5 sm:flex-row sm:items-center sm:justify-between",
  eyebrow: "text-xs font-semibold uppercase tracking-[0.14em] text-[var(--accent)]",
  servingName: "mt-1 text-xl font-semibold text-[var(--ink)]",
  servingSub: "mt-1 text-sm text-[var(--muted)]",
  servingBadge: "flex size-14 items-center justify-center rounded-xl bg-[var(--accent-soft)] text-lg font-semibold text-[var(--accent-dark)]",
  servingActions: "flex flex-wrap gap-2 px-5 py-4",
  mlAuto: "ml-auto",
  waitingHeader: "flex items-center justify-between border-b border-[var(--line)] px-5 py-4",
  cardTitle: "font-semibold text-[var(--ink)]",
  cardSubtitle: "mt-1 text-xs text-[var(--muted)]",
  waitingList: "divide-y divide-[var(--line)]",
  waitingRow: "flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center",
  positionBadge: "flex size-8 items-center justify-center rounded-lg bg-[var(--surface-muted)] text-sm font-semibold text-[var(--ink)]",
  memberInfo: "min-w-0 flex-1",
  memberName: "font-medium text-[var(--ink)]",
  memberSub: "mt-1 text-xs text-[var(--muted)]",
  memberWaitTime: "text-sm text-[var(--muted)]",
  rowActions: "flex gap-1",
  iconBtn: "rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--surface-muted)]",
  sidebarCard: "h-fit",
  activityHeader: "border-b border-[var(--line)] px-5 py-4",
  activityList: "space-y-5 p-5",
  activityItem: "flex gap-3",
  activityIconWrapper: "mt-1 flex size-7 shrink-0 items-center justify-center rounded-full bg-[var(--accent-soft)] text-[var(--accent)]",
  activityIcon: "size-3.5",
  activityAction: "text-sm leading-5 text-[var(--ink)]",
  activityTime: "mt-1 text-xs text-[var(--muted)]",
};

export { queueManagementScreenStyles };
